# Generated by Django 6.0.5 on 2026-05-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=50)),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponivel')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produto',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponivel')),
            ],
            options={
                'verbose_name': 'servico',
                'verbose_name_plural': 'servico',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valortotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'vender',
                'verbose_name_plural': 'vender',
                'ordering': ['nome'],
            },
        ),
    ]
