# Generated by Django 6.0.5 on 2026-06-03 21:29

from django.db import migrations, models
from datetime import timedelta

class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_rename_vender_historico_alter_historico_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'cliente',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='Sem categoria', max_length=50),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='servico',
            name='categoria',
            field=models.CharField(default='Sem categoria', max_length=50),
        ),
        migrations.AddField(
            model_name='servico',
            name='duracao',
            field=models.DurationField(default=timedelta(hours=1)),
        ),
        migrations.AddField(
            model_name='servico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='foto'),
        ),
    ]
