# Generated by Django 6.0.5 on 2026-06-03 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_cliente_produto_categoria_produto_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='duracao',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
