# Generated by Django 6.0.5 on 2026-06-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
    ]
