# Generated by Django 6.0.5 on 2026-06-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_alter_categoria_options_remove_categoria_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='categoria',
        ),
        migrations.AddField(
            model_name='historico',
            name='servicos',
            field=models.ManyToManyField(related_name='historicos', to='vendas.servico', verbose_name='Serviços'),
        ),
    ]
