# Generated by Django 6.0.5 on 2026-06-05 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_remove_servico_categoria_historico_servicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='historicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valortotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos', to='vendas.cliente', verbose_name='Cliente')),
                ('produto', models.ManyToManyField(related_name='historicos', to='vendas.produto', verbose_name='Produtos')),
                ('servico', models.ManyToManyField(related_name='historicos', to='vendas.servico', verbose_name='Serviços')),
            ],
            options={
                'verbose_name': 'historico',
                'verbose_name_plural': 'historico',
                'ordering': ['nome'],
            },
        ),
        migrations.DeleteModel(
            name='historico',
        ),
    ]
