# Generated by Django 6.0.5 on 2026-06-09 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_historicos_delete_historico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicos',
            options={'ordering': ['nome'], 'verbose_name': 'historicos', 'verbose_name_plural': 'historicos'},
        ),
        migrations.CreateModel(
            name='agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora do Agendamento')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmado'), ('F', 'Finalizado'), ('X', 'Cancelado')], default='P', max_length=1)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='vendas.cliente', verbose_name='Cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='vendas.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamento',
                'ordering': ['data_hora'],
            },
        ),
    ]
