# Generated by Django 6.0.5 on 2026-06-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_alter_historicos_options_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='Não informado', max_length=11),
        ),
    ]
