# Generated by Django 6.0.5 on 2026-06-15 01:24

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_remove_servico_quantidade_cliente_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['data_agendada'], 'verbose_name': 'agendamento', 'verbose_name_plural': 'agendamento'},
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_agendada',
            field=models.DateTimeField(default=timezone.now, verbose_name='Data do Agendamento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('X', 'Cancelado')], default='P', max_length=1),
        ),
    ]
